services:
  humanresourcemanagementsystem.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=HumanResourceDB;User=sa;Password=Your_password123;TrustServerCertificate=True;
      - Redis__ConnectionString=redis:6379
      - Redis__InstanceName=hrms
      - JwtSettings__Issuer=HumanResourceManagementSystem
      - JwtSettings__Audience=HumanResourceManagementSystem
      - JwtSettings__SignKey=hfudiakhuihljfioshkdfjledshxfkhdsjkhfkdsfklshdfkjsdh
    ports:
       - "8080:8080"
       - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - sqlserver
      - redis 

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  sqlserverdata:
  redis-data:  
